#include "helpers.hpp"
#include "builtins\CONTROL_FLOW.hpp"
#include "builtins\CPU.hpp"
#include "builtins\DESCRIPTOR.hpp"
#include "builtins\DEVICE.hpp"
#include "builtins\EXCEPTION.hpp"
#include "builtins\EXTERNAL_REGISTER.hpp"
#include "builtins\HINTER.hpp"
#include "builtins\INTERNAL_REGISTER.hpp"
#include "builtins\INTERRUPT.hpp"
#include "builtins\IO.hpp"
#include "builtins\MEMORY.hpp"
#include "builtins\RANDOMNESS.hpp"
#include "builtins\SYS.hpp"
#include "builtins\THREAD.hpp"
#include "builtins\TIMER.hpp"
#include "builtins\VM.hpp"


