#pragma once

/* STAT */
#define LURAMAS_PARSING_STAT_VAR "local "
#define LURAMAS_PARSING_STAT_WHILE "while"
#define LURAMAS_PARSING_STAT_REPEAT "repeat"
#define LURAMAS_PARSING_STAT_UNTIL "until"
#define LURAMAS_PARSING_STAT_BREAK "break"
#define LURAMAS_PARSING_STAT_CONTINUE "continue"
#define LURAMAS_PARSING_STAT_IF "if"
#define LURAMAS_PARSING_STAT_ELSE "else"
#define LURAMAS_PARSING_STAT_SCOPE_END "end"
#define LURAMAS_PARSING_STAT_EOL ";"
#define LURAMAS_PARSING_STAT_EQ "="
#define LURAMAS_PARSING_STAT_MULVAR_DELIMITER ","

/* EXPRS */
#define LURAMAS_PARSING_EXPR_OPEN "("
#define LURAMAS_PARSING_EXPR_CLOSE ")"
#define LURAMAS_PARSING_EXPR_WILD_CARD "?"
/* ARITH */
#define LURAMAS_PARSING_EXPR_ARITH_ADD "+"
#define LURAMAS_PARSING_EXPR_ARITH_SUB "-"
#define LURAMAS_PARSING_EXPR_ARITH_MUL "*"
#define LURAMAS_PARSING_EXPR_ARITH_DIV "/"
#define LURAMAS_PARSING_EXPR_ARITH_MOD "%"
#define LURAMAS_PARSING_EXPR_ARITH_AND "&"
#define LURAMAS_PARSING_EXPR_ARITH_OR "|"
#define LURAMAS_PARSING_EXPR_ARITH_XOR "^"
#define LURAMAS_PARSING_EXPR_ARITH_POW "^^"
#define LURAMAS_PARSING_EXPR_ARITH_SHL "<<"
#define LURAMAS_PARSING_EXPR_ARITH_SHR ">>"
#define LURAMAS_PARSING_EXPR_ARITH_IDIV "//"
/* UNARY */
#define LURAMAS_PARSING_EXPR_UNARY_BITNOT "~"
#define LURAMAS_PARSING_EXPR_UNARY_NOT "!"
#define LURAMAS_PARSING_EXPR_UNARY_LEN "#"
#define LURAMAS_PARSING_EXPR_UNARY_MINUS "-"
#define LURAMAS_PARSING_EXPR_UNARY_PLUS "+"
/* COND */
#define LURAMAS_PARSING_EXPR_TERNARY_START "if"
#define LURAMAS_PARSING_EXPR_TERNARY_THEN "then"
#define LURAMAS_PARSING_EXPR_TERNARY_ELSE "else"
#define LURAMAS_PARSING_EXPR_COND_EQ "=="
#define LURAMAS_PARSING_EXPR_COND_NE "!="
#define LURAMAS_PARSING_EXPR_COND_LT "<"
#define LURAMAS_PARSING_EXPR_COND_LTE "<="
#define LURAMAS_PARSING_EXPR_COND_GT ">"
#define LURAMAS_PARSING_EXPR_COND_GTE ">="
#define LURAMAS_PARSING_EXPR_COND_AND "&&"
#define LURAMAS_PARSING_EXPR_COND_OR "||"

#define LURAMAS_PARSING_EXPR_INTEGRAL_START "<"
#define LURAMAS_PARSING_EXPR_INTEGRAL_END ">"
#define LURAMAS_PARSING_EXPR_SIGNED "signed" LURAMAS_PARSING_EXPR_KEYWORD_INTEGRAL_START
#define LURAMAS_PARSING_EXPR_UNSIGNED "unsigned" LURAMAS_PARSING_EXPR_KEYWORD_INTEGRAL_START
