#pragma once
#include <cfg_tools/common.hpp>
#include <cpu_tracer/common.hpp>
#include <ranges>

namespace luramas::profile {

      /* Raw data from cpu_tracer */
      template <std::uint8_t MAX_LEN>
      struct raw_data {
            cpu_tracer::blocks::loader::save_data<MAX_LEN> sdata;              /* Save data */
            cpu_tracer::blocks::loader::analyze::analyzed_data<MAX_LEN> adata; /* Analyzed data */
            cpu_tracer::blocks::loader::analyze::edge_data edata;              /* Edge data */
      };

      /* Page locations by realpc generated by insts that call or return to a loc */
      using page_locs = boost::unordered_flat_set<cpu_tracer::address>;

      /* Instruction/Edge kinds */
      enum class inst_kind : std::uint8_t {
            normal,      /* Normal instruction */
            jump_to,     /* Jump instruction */
            call_to,     /* Call instruction */
            signaled_to, /* Instruction signaled execution */
            return_to    /* Return instruction (Instructions that use this will need to have every location documentated as possible else it will assume return is internally managed) */
      };

      /* Real pc or addr */
      struct real_or_addr {
            cpu_tracer::flag freal_pc = true; /* True if Real PC  */
            cpu_tracer::address real_pc = 0u; /* Real PC */
            cpu_tracer::address addr = 0u;    /* Virtual Address */

            real_or_addr() = default;
            real_or_addr(const cpu_tracer::flag freal_pc, const cpu_tracer::address pc)
                : freal_pc(freal_pc) {
                  if (this->freal_pc) {
                        this->real_pc = pc;
                        return;
                  }
                  this->addr = pc;
                  return;
            }
      };

      /* Edge to real PC, Inst kind acts like what couldve happend. If real PC actual address else its external address */
      using edge = std::pair<real_or_addr, inst_kind>;

      namespace externals {

            /* External function */
            template <typename T>
            struct external {
                  cpu_tracer::address loc = 0u; /* Location */
                  std::vector<T> args;          /* Arguments by arbitrary data */
                  std::vector<T> results;       /* Results by arbitrary data */
                  std::string name = "";        /* Name of the function */
            };

            /* External function: call address -> signature */
            template <typename T>
            using data = boost::unordered_flat_map<cpu_tracer::address, external<T>>;

            /* Emit external to data */
            template <typename T>
            void emit(data<T> &d, const cpu_tracer::address func_loc, const std::vector<T> &args, const std::vector<T> &results, const std::string &name) {
                  d[func_loc] = external<T>(func_loc, args, results, name);
                  return;
            }
      } // namespace externals

      /* Extra details */
      struct details {
            page_locs pages;                                       /* Pages by real PC */
            boost::unordered_flat_set<cpu_tracer::address> labels; /* Label of real PC */
      };

      namespace analyze {

            /* Generate page entries */
            template <std::uint8_t MAX_LEN>
            page_locs generate_pages(const raw_data<MAX_LEN> &raw) {

                  page_locs result;
                  for (const auto &[addr, b] : raw.sdata.block_map) {
                        if (!b) {
                              continue;
                        }
                        for (const auto &i : b->insts) {
                              switch (inst_kind(i.flags)) {
                                    case inst_kind::call_to:
                                    case inst_kind::return_to: {

                                          if (const auto it = raw.edata.successors.find(i.inst.real_pc); it != raw.edata.successors.end()) {
                                                const auto dests = it->second | std::views::transform([](const auto &e) { return e.dst_realpc; });
                                                result.insert(dests.begin(), dests.end());
                                          }
                                          break;
                                    }
                                    default: {
                                          break;
                                    }
                              }
                        }
                  }
                  return result;
            }

            /* CPU Tracer graph */
            template <std::uint8_t MAX_LEN>
            using graph = cpu_tracer::blocks::graph::Graph<MAX_LEN>;

            /* Calls CFG linearization */
            template <std::uint8_t MAX_LEN>
            inline boost::container::vector<cfg_tools::basic_block<graph<MAX_LEN>>> linearize(const graph<MAX_LEN> &g) {
                  return cfg_tools::linearize<graph<MAX_LEN>>(g);
            }

      } // namespace analyze

} // namespace luramas::profile